--BẢNG DONVI

alter session set container = QLDuLieuNoiBo ; 
alter session set CURRENT_SCHEMA = QLDL ; 
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('CNTT', 'Khoa Công nghệ thông tin', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('HOA', 'Khoa Hóa học', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('TOAN', 'Khoa Toán học', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PDT', 'Phòng Đào tạo', 'Phòng', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PTV', 'Phòng Tài vụ', 'Phòng', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('VLY', 'Khoa Vật lý', 'Khoa', NULL);
INSERT INTO DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PQTTB', 'Phòng Quản trị thiết bị', 'Phòng', NULL);

-- Bảng NHANVIEN
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV01', 'Nguyen Van A', 'Nam', TO_DATE('1980-05-20','YYYY-MM-DD'), 12000000, 1000000, '0912345678', 'TRGDV', 'CNTT');
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV02', 'Tran Thi B', 'Nữ', TO_DATE('1982-11-15','YYYY-MM-DD'), 11000000, 900000, '0987654321', 'NVCB', 'CNTT');
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV03', 'Le Van C', 'Nam', TO_DATE('1975-09-10','YYYY-MM-DD'), 15000000, 1500000, '0934567890', 'TRGDV', 'PDT');
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV04', 'Pham Thi D', 'Nữ', TO_DATE('1990-01-01','YYYY-MM-DD'), 10000000, 700000, '0923456789', 'NV PĐT', 'PDT');
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV05', 'Dang Van E', 'Nam', TO_DATE('1985-07-25','YYYY-MM-DD'), 13000000, 1200000, '0909123456', 'TRGDV', 'HOA');
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV06', 'Bui Thi F', 'Nữ', TO_DATE('1979-03-18','YYYY-MM-DD'), 14000000, 1100000, '0945678901', 'TRGDV', 'PTV');
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV07', 'Do Van G', 'Nam', TO_DATE('1983-08-08','YYYY-MM-DD'), 12500000, 1000000, '0911222333', 'GV', 'TOAN');
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV08', 'Ha Thi Thu H', 'Nữ', TO_DATE('1989-12-08','YYYY-MM-DD'), 15000000, 2000000, '0977150880', 'TRGDV', 'VLY');
-- Nhân viên Phòng Kế Toán (PKT)
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES (
  'NV09', 'Nguyen Van I', 'Nam', TO_DATE('1984-02-14','YYYY-MM-DD'),
  11500000, 800000, '0919999999', 'NV PKT', 'PTV'
);

-- Nhân viên Tổ chức Hành chính (TCHC)
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES (
  'NV10', 'Tran Thi K', 'Nữ', TO_DATE('1986-07-21','YYYY-MM-DD'),
  11800000, 850000, '0928888888', 'NV TCHC', 'PQTTB'
);

-- Nhân viên Công tác Sinh viên (CTSV)
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES (
  'NV11', 'Le Van M', 'Nam', TO_DATE('1988-11-11','YYYY-MM-DD'),
  11700000, 870000, '0937777777', 'NV CTSV', 'PDT'
);




--UPDATE BẢNG DONVI
UPDATE DONVI SET TRGDV = 'NV01' WHERE MADV = 'CNTT';
UPDATE DONVI SET TRGDV = 'NV05' WHERE MADV = 'HOA';
UPDATE DONVI SET TRGDV = 'NV06' WHERE MADV = 'PTV';
UPDATE DONVI SET TRGDV = 'NV03' WHERE MADV = 'PDT';
UPDATE DONVI SET TRGDV = 'NV08' WHERE MADV = 'VLY';

--BẢNG SINHVIEN
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG) VALUES ('SV001', 'Nguyen Thi Mai', 'Nữ', TO_DATE('2003-04-15','YYYY-MM-DD'), 'Hà Nội', '0911111111', 'CNTT', 'Đang học');
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG) VALUES ('SV002', 'Tran Van Binh', 'Nam', TO_DATE('2002-12-20','YYYY-MM-DD'), 'Hải Phòng', '0922222222', 'HOA', 'Đang học');
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG) VALUES ('SV003', 'Le Thi Cam', 'Nữ', TO_DATE('2001-06-10','YYYY-MM-DD'), 'Đà Nẵng', '0933333333', 'CNTT', 'Nghỉ học');
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG) VALUES ('SV004', 'Pham Van Duy', 'Nam', TO_DATE('2003-01-05','YYYY-MM-DD'), 'TP.HCM', '0944444444', 'TOAN', 'Đang học');
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG) VALUES ('SV005', 'Do Thi Em', 'Nữ', TO_DATE('2000-11-11','YYYY-MM-DD'), 'Cần Thơ', '0955555555', 'CNTT', 'Bảo lưu');
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG) VALUES ('SV006', 'Hoang Van Hoa', 'Nam', TO_DATE('2003-03-30','YYYY-MM-DD'), 'Bắc Giang', '0966666666', 'HOA', 'Đang học');
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA, TINHTRANG) VALUES ('SV007', 'Ngo Thi Lan', 'Nữ', TO_DATE('2002-09-09','YYYY-MM-DD'), 'Quảng Ninh', '0977777777', 'VLY', 'Đang học');

--BẢNG HOCPHAN
INSERT INTO HOCPHAN VALUES ('HP001', 'Cấu trúc dữ liệu', 3, 30, 15, 'CNTT');
INSERT INTO HOCPHAN VALUES ('HP002', 'Giải tích 1', 4, 45, 15, 'TOAN');
INSERT INTO HOCPHAN VALUES ('HP003', 'Lý thuyết hóa học', 3, 35, 20, 'HOA');
INSERT INTO HOCPHAN VALUES ('HP004', 'Lập trình Java', 3, 30, 20, 'CNTT');
INSERT INTO HOCPHAN VALUES ('HP005', 'Vật lý đại cương', 3, 40, 15, 'VLY');
INSERT INTO HOCPHAN VALUES ('HP006', 'Cơ sở dữ liệu', 3, 30, 15, 'CNTT');
INSERT INTO HOCPHAN VALUES ('HP007', 'Xác suất thống kê', 3, 30, 10, 'TOAN');

--BẢNG MOMON
INSERT INTO MOMON VALUES ('MM001', 'HP001', 'NV01', 1, 2024);
INSERT INTO MOMON VALUES ('MM002', 'HP002', 'NV07', 1, 2024);
INSERT INTO MOMON VALUES ('MM003', 'HP003', 'NV05', 2, 2024);
INSERT INTO MOMON VALUES ('MM004', 'HP004', 'NV02', 2, 2024);
INSERT INTO MOMON VALUES ('MM005', 'HP005', 'NV08', 1, 2024);
INSERT INTO MOMON VALUES ('MM006', 'HP006', 'NV02', 3, 2024);
INSERT INTO MOMON VALUES ('MM007', 'HP007', 'NV07', 2, 2024);



INSERT INTO MOMON VALUES ('MM008', 'HP001', 'NV03', 2, 2025);
INSERT INTO MOMON VALUES ('MM009', 'HP002', 'NV04', 2, 2025);
INSERT INTO MOMON VALUES ('MM010', 'HP003', 'NV01', 2, 2025);
INSERT INTO MOMON VALUES ('MM011', 'HP004', 'NV05', 2, 2025);
INSERT INTO MOMON VALUES ('MM012', 'HP005', 'NV06', 2, 2025);
INSERT INTO MOMON VALUES ('MM013', 'HP006', 'NV02', 2, 2025);
INSERT INTO MOMON VALUES ('MM014', 'HP007', 'NV08', 2, 2025);
INSERT INTO MOMON VALUES ('MM015', 'HP001', 'NV07', 2, 2025);
INSERT INTO MOMON VALUES ('MM016', 'HP002', 'NV03', 2, 2025);
INSERT INTO MOMON VALUES ('MM017', 'HP003', 'NV06', 2, 2025);


--BẢNG DANGKY
INSERT INTO DANGKY VALUES ('SV001', 'MM001', 8.5, 9.0, 8.0, 8.5);
INSERT INTO DANGKY VALUES ('SV001', 'MM004', 7.5, 8.0, 7.0, 7.5);
INSERT INTO DANGKY VALUES ('SV002', 'MM003', 6.0, 6.5, 7.0, 6.5);
INSERT INTO DANGKY VALUES ('SV004', 'MM002', 9.0, 9.5, 9.0, 9.2);
INSERT INTO DANGKY VALUES ('SV005', 'MM006', 7.0, 8.0, 7.5, 7.5);
INSERT INTO DANGKY VALUES ('SV006', 'MM005', 6.5, 7.0, 6.0, 6.5);
INSERT INTO DANGKY VALUES ('SV007', 'MM007', 8.0, 7.5, 7.0, 7.5);



-- Cập nhật dữ liệu mẫu cho cột COSO
UPDATE QLDL.NHANVIEN SET COSO = 'Cơ sở 1' WHERE MADV IN ('CNTT', 'TOAN', 'PDT', 'PTV');
UPDATE QLDL.NHANVIEN SET COSO = 'Cơ sở 2' WHERE MADV IN ('HOA', 'VLY', 'PQTTB');
UPDATE QLDL.SINHVIEN SET COSO = 'Cơ sở 1' WHERE KHOA IN ('CNTT', 'TOAN');
UPDATE QLDL.SINHVIEN SET COSO = 'Cơ sở 2' WHERE KHOA IN ('HOA', 'VLY'); 


-- Thêm thông báo với nhãn t1: Dành cho tất cả trưởng đơn vị
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo họp trưởng đơn vị toàn trường.', CHAR_TO_LABEL('THONGBAO_POLICY', 'TRUONGDV'));

-- Thêm thông báo với nhãn t2: Dành cho tất cả nhân viên
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo nghỉ lễ dành cho toàn thể nhân viên.', CHAR_TO_LABEL('THONGBAO_POLICY', 'NHANVIEN'));

-- Thêm thông báo với nhãn t3: Dành cho tất cả sinh viên
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo lịch thi học kỳ cho sinh viên.', CHAR_TO_LABEL('THONGBAO_POLICY', 'SINHVIEN'));

-- Thêm thông báo với nhãn t4: Dành cho sinh viên khoa Hóa cơ sở 1
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo seminar khoa Hóa cơ sở 1.', CHAR_TO_LABEL('THONGBAO_POLICY', 'SINHVIEN:HOA:COSO1'));

-- Thêm thông báo với nhãn t5: Dành cho sinh viên khoa Hóa cơ sở 2
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo thực hành thí nghiệm khoa Hóa cơ sở 2.', CHAR_TO_LABEL('THONGBAO_POLICY', 'SINHVIEN:HOA:COSO2'));

-- Thêm thông báo với nhãn t6: Dành cho sinh viên khoa Hóa cả 2 cơ sở
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo hội thảo khoa Hóa cả hai cơ sở.', CHAR_TO_LABEL('THONGBAO_POLICY', 'SINHVIEN:HOA:COSO1,COSO2'));

-- Thêm thông báo với nhãn t7: Dành cho tất cả sinh viên cả 2 cơ sở
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo ngày hội sinh viên toàn trường.', CHAR_TO_LABEL('THONGBAO_POLICY', 'SINHVIEN::COSO1,COSO2'));

-- Thêm thông báo với nhãn t8: Dành cho trưởng khoa Hóa cơ sở 1
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo họp trưởng khoa Hóa cơ sở 1.', CHAR_TO_LABEL('THONGBAO_POLICY', 'TRUONGDV:HOA:COSO1'));

-- Thêm thông báo với nhãn t9: Dành cho trưởng khoa Hóa cả 2 cơ sở
INSERT INTO THONGBAO (ID_THONGBAO, NOIDUNG, LABEL)
VALUES (thongbao_seq.NEXTVAL, 'Thông báo kế hoạch phát triển khoa Hóa cả hai cơ sở.', CHAR_TO_LABEL('THONGBAO_POLICY', 'TRUONGDV:HOA:COSO1,COSO2'));




