--Kết nối vào CDB (root container)
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- kiểm tra có tồn tại pdb này chưa
DECLARE 
    v_count NUMBER;
BEGIN

    SELECT COUNT(*) INTO v_count 
    FROM dba_pdbs 
    WHERE pdb_name = 'QLDULIEUNOIBO';

    IF v_count != 0 THEN
        DBMS_OUTPUT.PUT_LINE('PDB QLDulieuNoiBo đã tồn tại, tiến hành xóa.');
        EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE QLDULIEUNOIBO CLOSE IMMEDIATE';
        EXECUTE IMMEDIATE 'DROP PLUGGABLE DATABASE QLDULIEUNOIBO INCLUDING DATAFILES';
        DBMS_OUTPUT.PUT_LINE('PDB QLDulieuNoiBo đã được xóa.');
     else 
          DBMS_OUTPUT.PUT_LINE('PDB QLNhanVien_22120317 đã được xóa.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Lỗi: ' || SQLERRM);
END;
/

--chỉ định thư mục mặc định nơi Oracle sẽ tạo các tệp dữ liệu (datafile) cho PDB mới;
BEGIN
  DECLARE
     v_path VARCHAR2(400); -- Biến để lưu đường dẫn
  BEGIN
     -- Lấy đường dẫn từ dba_data_files và gán vào biến
     SELECT SUBSTR(file_name, 1, INSTR(file_name, '\', -1)-1)
     INTO v_path
     FROM dba_data_files 
     WHERE tablespace_name = 'SYSTEM' 
     AND ROWNUM = 1;

     -- Thực thi lệnh ALTER SYSTEM với giá trị từ biến
     EXECUTE IMMEDIATE 
        'ALTER SYSTEM SET DB_CREATE_FILE_DEST = ''' || v_path || '''';
  END;
END;
/
-- Tạo PDB mới với tên QLDuLieuNoiBo
CREATE PLUGGABLE DATABASE QLDulieuNoiBo
  ADMIN USER QLDL IDENTIFIED BY 123456;

-- Mở PDB để sử dụng
ALTER PLUGGABLE DATABASE QLDulieuNoiBo OPEN;

-- Chuyển session sang PDB mới
ALTER SESSION SET CONTAINER = QLDulieuNoiBo;
-- Cấp quyền 
GRANT UNLIMITED TABLESPACE TO QLDL;
GRANT CONNECT TO QLDL WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO QLDL;
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO QLDL;
GRANT CREATE SYNONYM, CREATE DATABASE LINK , UNLIMITED TABLESPACE TO QLDL;
GRANT EXECUTE ON DBMS_FGA TO QLDL;
GRANT RESOURCE TO QLDL with admin option;
GRANT CREATE USER, CREATE ROLE, ALTER USER, ALTER ANY ROLE, DROP USER, DROP ANY ROLE TO QLDL;
GRANT CREATE TRIGGER TO QLDL;
GRANT EXECUTE ON SYS.DBMS_SESSION TO QLDL;
GRANT EXECUTE ON DBMS_CRYPTO TO QLDL; 
GRANT ADMINISTER DATABASE TRIGGER TO QLDL;

---- Lưu trạng thái của PDB để mở tự động khi khởi động lại CDB
--ALTER PLUGGABLE DATABASE QLDulieuNoiBo SAVE STATE;
--ALTER SESSION SET CONTAINER = CDB$ROOT;

--  Chuyển sang PDB mới DE THEM BANG 
ALTER SESSION SET CONTAINER = QLDulieuNoiBo;
alter session set CURRENT_SCHEMA = QLDL;

-- tạo table 
-- Bảng NHANVIEN phải tạo trước DONVI do DONVI tham chiếu đến NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI VARCHAR2(5) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    LUONG NUMBER(10,2),
    PHUCAP NUMBER(10,2),
    DT VARCHAR2(20),
    VAITRO VARCHAR2(20) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGDV')),
    MADV VARCHAR2(10),
    COSO VARCHAR2(10 BYTE)
);

CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(100),
    LOAIDV VARCHAR2(20) CHECK (LOAIDV IN ('Khoa', 'Phòng')),
    TRGDV VARCHAR2(10), -- Tham chiếu đến NHANVIEN
    CONSTRAINT fk_trgdv FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANV)
);

-- Cập nhật lại khóa ngoại ở NHANVIEN sau khi DONVI tồn tại
ALTER TABLE NHANVIEN
ADD CONSTRAINT fk_nhanvien_donvi FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

-- SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI VARCHAR2(5) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    DCHI VARCHAR2(200),
    DT VARCHAR2(20),
    KHOA VARCHAR2(10), -- MADV tương ứng bên DONVI
    TINHTRANG VARCHAR2(20),
    COSO VARCHAR2(10 BYTE), 
    CONSTRAINT fk_sinhvien_khoa FOREIGN KEY (KHOA) REFERENCES DONVI(MADV)
);

-- HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(100),
    SOTC NUMBER(2),
    STLT NUMBER(3),
    STTH NUMBER(3),
    MADV VARCHAR2(10),
    CONSTRAINT fk_hocphan_donvi FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

-- MOMON
CREATE TABLE MOMON (
    MAMM VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK NUMBER(1) CHECK (HK IN (1,2,3)),
    NAM NUMBER(4),
    CONSTRAINT fk_momon_hocphan FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    CONSTRAINT fk_momon_giangvien FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANV)
);

-- DANGKY
CREATE TABLE DANGKY (
    MASV VARCHAR2(10),
    MAMM VARCHAR2(10),
    DIEMTH NUMBER(5,2),
    DIEMQT NUMBER(5,2),
    DIEMCK NUMBER(5,2),
    DIEMTK NUMBER(5,2),
    PRIMARY KEY (MASV, MAMM),
    CONSTRAINT fk_dangky_sv FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT fk_dangky_mamon FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);

--tao bảng THONGBAO
CREATE TABLE THONGBAO(
    ID_THONGBAO NUMBER PRIMARY KEY,
    NOIDUNG     VARCHAR2(4000),
    ThoiGian TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DiaDiem NVARCHAR2(50)
);

CREATE SEQUENCE thongbao_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE nhanvien_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE momon_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE sinhvien_seq START WITH 1 INCREMENT BY 1;

