--Kết nối vào CDB (root container)
--ALTER SESSION SET CONTAINER = CDB$ROOT;
----chỉ định thư mục mặc định nơi Oracle sẽ tạo các tệp dữ liệu (datafile) cho PDB mới;
--BEGIN
--   DECLARE
--      v_path VARCHAR2(400); -- Biến để lưu đường dẫn
--   BEGIN
--      -- Lấy đường dẫn từ dba_data_files và gán vào biến
--      SELECT SUBSTR(file_name, 1, INSTR(file_name, '\', -1)-1)
--      INTO v_path
--      FROM dba_data_files 
--      WHERE tablespace_name = 'SYSTEM' 
--      AND ROWNUM = 1;
--
--      -- Thực thi lệnh ALTER SYSTEM với giá trị từ biến
--      EXECUTE IMMEDIATE 
--         'ALTER SYSTEM SET DB_CREATE_FILE_DEST = ''' || v_path || '''';
--   END;
--END;
--/
---- Tạo PDB mới với tên QLDuLieuNoiBo
--CREATE PLUGGABLE DATABASE QLDulieuNoiBo
--   ADMIN USER QLDL IDENTIFIED BY 123456;
--
---- Mở PDB để sử dụng
--ALTER PLUGGABLE DATABASE QLDulieuNoiBo OPEN;
--
---- Chuyển session sang PDB mới
--ALTER SESSION SET CONTAINER = QLDulieuNoiBo;
---- Cấp quyền 
GRANT UNLIMITED TABLESPACE TO QLDL;
GRANT CONNECT TO QLDL WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO QLDL;
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO QLDL;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO QLDL;
GRANT CREATE USER, CREATE ROLE, ALTER USER, ALTER ANY ROLE, DROP USER, DROP ANY ROLE TO QLDL;
GRANT CREATE TRIGGER TO QLDL;
GRANT EXECUTE ON SYS.DBMS_SESSION TO QLDL;
GRANT EXECUTE ON DBMS_CRYPTO TO QLDL; 
---- Lưu trạng thái của PDB để mở tự động khi khởi động lại CDB
--ALTER PLUGGABLE DATABASE QLDulieuNoiBo SAVE STATE;
--ALTER SESSION SET CONTAINER = CDB$ROOT;

--  Chuyển sang PDB mới DE THEM BANG 
ALTER SESSION SET CONTAINER = QLDulieuNoiBo;
alter session set CURRENT_SCHEMA = QLDL;

-- tạo table 
CREATE TABLE DONVI (
    MADV CHAR(5) PRIMARY KEY,
    TENDV VARCHAR2(100),
    LOAIDV VARCHAR2(20) CHECK (LOAIDV IN ('Khoa', 'Phòng')),
    TRGDV CHAR(5) -- Tham chiếu đến NHANVIEN
);

CREATE TABLE NHANVIEN (
    MANV CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI varCHAR2(5) CHECK (PHAI IN ('Nam', 'Nữ')), -- Male / Female
    NGSINH DATE,
    LUONG NUMBER(10,2),
    PHUCAP NUMBER(10,2),
    DT VARCHAR2(20),
    VAITRO VARCHAR2(20) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGDV')),
    MADV CHAR(5),
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

CREATE TABLE SINHVIEN ( 
    MASV CHAR(8) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI varCHAR2(5) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    DCHI VARCHAR2(200),
    DT VARCHAR2(20),
    KHOA CHAR(5), -- MADV tương ứng bên DONVI
    TINHTRANG VARCHAR2(20),
    FOREIGN KEY (KHOA) REFERENCES DONVI(MADV)
);

CREATE TABLE HOCPHAN (
    MAHP CHAR(8) PRIMARY KEY,
    TENHP VARCHAR2(100),
    SOTC NUMBER(2),
    STLT NUMBER(3), -- số tiết lý thuyết
    STTH NUMBER(3), -- số tiết thực hành
    MADV CHAR(5),
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

CREATE TABLE MOMON (
    MAMM CHAR(10) PRIMARY KEY,
    MAHP CHAR(8),
    MAGV CHAR(5),
    HK NUMBER(1) CHECK (HK IN (1,2,3)),
    NAM NUMBER(4),
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE DANGKY (
    MASV CHAR(8),
    MAMM CHAR(10),
    DIEMTH NUMBER(5,2),
    DIEMQT NUMBER(5,2),
    DIEMCK NUMBER(5,2),
    DIEMTK NUMBER(5,2),
    PRIMARY KEY (MASV, MAMM),
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);

-- them khoa ngoai
ALTER TABLE DONVI
ADD CONSTRAINT fk_trgdv FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANV);

-- Tạo các role tương ứng với các vai trò
CREATE ROLE ROLE_NVCB;
CREATE ROLE ROLE_GV;
CREATE ROLE ROLE_NV_PDT;
CREATE ROLE ROLE_NV_PKT;
CREATE ROLE ROLE_NV_TCHC;
CREATE ROLE ROLE_NV_CTSV;
CREATE ROLE ROLE_TRGDV;

-- Chỉ cần quyền đọc chung
GRANT SELECT ON NHANVIEN TO ROLE_NVCB;
GRANT SELECT ON SINHVIEN TO ROLE_NVCB;
GRANT SELECT ON HOCPHAN TO ROLE_NVCB;

-- Xem danh sách môn dạy, sinh viên lớp mình
GRANT SELECT ON MOMON TO ROLE_GV;
GRANT SELECT ON SINHVIEN TO ROLE_GV;

-- Nhập điểm vào bảng DANGKY
GRANT SELECT, UPDATE (DIEMTH, DIEMQT, DIEMCK, DIEMTK) ON DANGKY TO ROLE_GV;

-- Toàn quyền với môn học, mở môn và đăng ký
GRANT SELECT, INSERT, UPDATE, DELETE ON HOCPHAN TO ROLE_NV_PDT;
GRANT SELECT, INSERT, UPDATE, DELETE ON MOMON TO ROLE_NV_PDT;
GRANT SELECT, INSERT, UPDATE, DELETE ON DANGKY TO ROLE_NV_PDT;
GRANT SELECT, INSERT, UPDATE, DELETE ON SINHVIEN TO ROLE_NV_PDT;

-- Xem thông tin điểm
GRANT SELECT ON DANGKY TO ROLE_NV_PKT;

-- Quản lý thông tin nhân viên
GRANT SELECT, INSERT, UPDATE, DELETE ON NHANVIEN TO ROLE_NV_TCHC;

-- Xem thông tin sinh viên
GRANT SELECT ON SINHVIEN TO ROLE_NV_CTSV;

-- Xem thông tin đơn vị, nhân viên, sinh viên
GRANT SELECT ON DONVI TO ROLE_TRGDV;
GRANT SELECT ON NHANVIEN TO ROLE_TRGDV;
GRANT SELECT ON SINHVIEN TO ROLE_TRGDV;


