
--1. Tạo các vai trò tương ứng (roles)
CREATE ROLE ROLE_GV;
CREATE ROLE ROLE_NV_PDT;
CREATE ROLE ROLE_NV_PKT;
CREATE ROLE ROLE_NV_CTSV;
CREATE ROLE ROLE_SINHVIEN;
-- Vai trò nhân viên cơ bản
CREATE ROLE ROLE_NVCB;

-- Vai trò trưởng đơn vị
CREATE ROLE ROLE_TRGDV;

-- Vai trò nhân viên tổ chức hành chính
CREATE ROLE ROLE_TCHC;


-- GRANT SELECT ON QLDL.DONVI TO ROLE_NV_CTSV; --// để test sinh viên xem thông tin đơn vị
 GRANT SELECT ON QLDL.NHANVIEN_SEQ to  ROLE_TCHC;
 GRANT SELECT ON QLDL.momon_seq to  ROLE_NV_PDT;

 GRANT SELECT ON QLDL.sinhvien_seq to  ROLE_NV_CTSV;


 GRANT EXECUTE ON QLDL.CURRENT_HK to  ROLE_NV_PDT;
 GRANT EXECUTE ON QLDL.CURRENT_NAM to  ROLE_NV_PDT;



