-- Tạo user cho NV01
CREATE USER NV01 IDENTIFIED BY nv01pass;
GRANT CONNECT TO NV01;
GRANT ROLE_GV,ROLE_TRGDV,ROLE_NV_PDT TO NV01;

-- Tạo user cho NV02
CREATE USER NV02 IDENTIFIED BY nv02pass;
GRANT CONNECT TO NV02;

-- Tạo user cho NV03
CREATE USER NV03 IDENTIFIED BY nv03pass;
GRANT CONNECT TO NV03;

-- Tạo user cho NV04
CREATE USER NV04 IDENTIFIED BY nv04pass;
GRANT CONNECT TO NV04;

-- Tạo user cho NV05
CREATE USER NV05 IDENTIFIED BY nv05pass;
GRANT CONNECT TO NV05;

-- Tạo user cho NV05
CREATE USER SV001 IDENTIFIED BY 123;
GRANT CONNECT TO SV001;
    
GRANT ROLE_SINHVIEN to SV001;
