CONNECT QLDL/123456@localhost:1521/QLDULIEUNOIBO;

--1. Tạo các vai trò tương ứng (roles)
CREATE ROLE ROLE_GV;
CREATE ROLE ROLE_NV_PDT;
CREATE ROLE ROLE_NV_PKT;
CREATE ROLE ROLE_NV_CTSV;
CREATE ROLE ROLE_SINHVIEN;
-- Vai trò nhân viên cơ bản
CREATE ROLE ROLE_NVCB;

-- Vai trò trưởng đơn vị
CREATE ROLE ROLE_TRGDV;

-- Vai trò nhân viên tổ chức hành chính
CREATE ROLE ROLE_TCHC;

--2. Tạo view và policy phù hợp với từng vai trò
--2.1. NVCB – Xem và sửa ĐT của chính mình
-- View cho NVCB chỉ xem thông tin chính mình
CREATE OR REPLACE VIEW VIEW_NHANVIEN_NVCB AS
SELECT * FROM NHANVIEN
WHERE SYS_CONTEXT('USERENV', 'SESSION_USER') = MANV;

-- Cho phép sửa số điện thoại của chính mình bằng trigger
CREATE OR REPLACE TRIGGER trg_update_dt_nv
BEFORE UPDATE ON NHANVIEN
FOR EACH ROW
WHEN (OLD.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'))
BEGIN
   IF :NEW.DT != :OLD.DT THEN
      NULL; -- Cho phép cập nhật
   ELSE
      :NEW.DT := :OLD.DT; -- Không thay đổi gì
   END IF;
END;
/
-- Cấp quyền cho role
GRANT SELECT, UPDATE (DT) ON QLDL.VIEW_NHANVIEN_NVCB TO ROLE_NVCB;
--2.2 Tất cả nhân viên thuộc các vai trò còn lại đều có quyền của vai trò “NVCB”
GRANT ROLE_NVCB TO ROLE_GV;
GRANT ROLE_NVCB TO ROLE_NV_PDT;
GRANT ROLE_NVCB TO ROLE_NV_PKT;
GRANT ROLE_NVCB TO ROLE_NV_CTSV;
GRANT ROLE_NVCB TO ROLE_TRGDV;
GRANT ROLE_NVCB TO ROLE_TCHC;

--2.3. TRGDV – Xem nhân viên đơn vị mình, ẩn lương & phụ cấp
-- View ẩn LUONG và PHUCAP cho TRGDV
CREATE OR REPLACE VIEW VIEW_NHANVIEN_TRGDV AS
SELECT MANV, HOTEN, PHAI, NGSINH, DT, VAITRO, MADV
FROM NHANVIEN
WHERE MADV = (
  SELECT MADV FROM DONVI WHERE TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER')
);

-- Cấp quyền cho role
GRANT SELECT ON QLDL.VIEW_NHANVIEN_TRGDV TO ROLE_TRGDV;

--2.4. NV TCHC – Toàn quyền trên NHANVIEN
GRANT SELECT, INSERT, UPDATE, DELETE ON NHANVIEN TO ROLE_TCHC;



