--Tạo các view và cấp quyền theo vai trò
--2.1. Giảng viên (GV) – Xem phân công giảng dạy của chính mình
CREATE OR REPLACE VIEW VIEW_MOMON_GV AS
SELECT * FROM MOMON
WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON VIEW_MOMON_GV TO ROLE_GV;

--2.2. Nhân viên PĐT – Toàn quyền trên học kỳ hiện tại
--Function trả về học kỳ hiện tại
CREATE OR REPLACE FUNCTION CURRENT_HK RETURN NUMBER IS
    v_month NUMBER := EXTRACT(MONTH FROM SYSDATE);
    v_hk    NUMBER;
BEGIN
    IF v_month BETWEEN 9 AND 12 THEN
        v_hk := 1;
    ELSIF v_month BETWEEN 1 AND 4 THEN
        v_hk := 2;
    ELSE
        v_hk := 3;
    END IF;
    RETURN v_hk;
END;
/
--Function trả về năm học hiện tại
CREATE OR REPLACE FUNCTION CURRENT_NAM RETURN NUMBER IS
    v_month NUMBER := EXTRACT(MONTH FROM SYSDATE);
    v_year  NUMBER := EXTRACT(YEAR FROM SYSDATE);
    v_nam   NUMBER;
BEGIN
    IF v_month BETWEEN 9 AND 12 THEN
        v_nam := v_year;
    ELSE
        v_nam := v_year - 1;
    END IF;
    RETURN v_nam;
END;
/
CREATE OR REPLACE VIEW VIEW_MOMON_PDT AS
SELECT * FROM MOMON
WHERE HK = CURRENT_HK() AND NAM = CURRENT_NAM();

-- Cấp toàn quyền trên dữ liệu hiện tại
GRANT SELECT, INSERT, UPDATE, DELETE ON VIEW_MOMON_PDT TO ROLE_NV_PDT;

-- 2.3. Trưởng đơn vị (TRGDV) – Xem các giảng viên thuộc đơn vị mình
CREATE OR REPLACE VIEW VIEW_MOMON_TRGDV AS
SELECT M.*
FROM MOMON M
JOIN NHANVIEN GV ON M.MAGV = GV.MANV
JOIN DONVI D ON GV.MADV = D.MADV
WHERE D.TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON VIEW_MOMON_TRGDV TO ROLE_TRGDV;

-- 2.4. Sinh viên – Xem học phần mở do khoa mình phụ trách
CREATE OR REPLACE VIEW VIEW_MOMON_SV AS
SELECT M.*
FROM MOMON M
JOIN HOCPHAN HP ON M.MAHP = HP.MAHP
JOIN SINHVIEN SV ON SYS_CONTEXT('USERENV', 'SESSION_USER') = SV.MASV
WHERE HP.MADV = SV.KHOA;

GRANT SELECT ON VIEW_MOMON_SV TO ROLE_SINHVIEN;
